---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/add-house":
    post:
      summary: Creates a house
      tags:
      - houses
      parameters: []
      responses:
        '201':
          description: house created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                price:
                  type: integer
                photo:
                  type: string
              required:
              - name
              - location
              - price
              - photo
          application/xml:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
                price:
                  type: integer
                photo:
                  type: string
              required:
              - name
              - location
              - price
              - photo
  "/api/v1/houses/{id}":
    get:
      summary: Retrieves a house
      tags:
      - Houses
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: house found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  location:
                    type: string
                  price:
                    type: integer
                  photo:
                    type: string
                required:
                - id
                - name
                - lacation
                - price
                - photo
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  location:
                    type: string
                  price:
                    type: integer
                  photo:
                    type: string
                required:
                - id
                - name
                - lacation
                - price
                - photo
        '404':
          description: house not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
